name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-actions@v1.3.2
    - run: flutter pub get
    #TODO: add `flutter test`
    - run: flutter build apk
