name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with: 
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: '1.17.0'
        channel: 'stable'
    - name: Build APKs
      run: |
        flutter pub get
        flutter build apk --release 
        flutter build apk --release --split-per-abi
    - name: Add and Commit APKs
      run: |
        mkdir -p output
        cp build/app/outputs/flutter-apk/* output/
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git add output
        git commit -m "Update APKs"
    - name: Push APKs
      uses: ad-m/github-push-action@master
      with:
        branch: deployment
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
    - name: Update release
      uses: johnwbyrd/update-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ./build/app/outputs/flutter-apk/app-release.apk ./build/app/outputs/flutter-apk/app-arm64-v8a-release.apk ./build/app/outputs/flutter-apk/app-x86_64-release.apk ./build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
#     - name: Create Release
#       id: create-release
#       uses: actions/create-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         tag_name: ${{ github.ref }}
#         release_name: Release ${{ github.ref }}
#         draft: false
#         prerelease: false
#     - name: Upload Release Assets
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create-release.outputs.upload_url }}
#         asset_path: ./build/app/outputs/flutter-apk/app-release.apk
#         asset_name: app-release.apk
#         asset_content_type: application/java-archive
#     - name: Upload Release Assets
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create-release.outputs.upload_url }}
#         asset_path: ./build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
#         asset_name: app-arm64-v8a-release.apk
#         asset_content_type: application/java-archive
#     - name: Upload Release Assets
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create-release.outputs.upload_url }}
#         asset_path: ./build/app/outputs/flutter-apk/app-x86_64-release.apk
#         asset_name: app-x86_64-release.apk
#         asset_content_type: application/java-archive
#     - name: Upload Release Assets
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create-release.outputs.upload_url }}
#         asset_path: ./build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
#         asset_name: app-armeabi-v7a-release.apk
#         asset_content_type: application/java-archive
